import type { NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';

const Animator = dynamic(
  // @ts-ignore
  import('react-scroll-motion').then((it) => it.Animator),
  { ssr: false }
);

import {
  ScrollContainer,
  ScrollPage,
  batch,
  Fade,
  FadeIn,
  FadeOut,
  Move,
  MoveIn,
  MoveOut,
  Sticky,
  StickyIn,
  StickyOut,
  Zoom,
  ZoomIn,
  ZoomOut,
} from 'react-scroll-motion';
import Navbar from '../components/Navbar';
import { IconChevronDown, IconPlus } from '@tabler/icons';
import Image from 'next/image';

const introPage1 = (
  <div className="w-screen px-16 bg-[#ed4851] h-screen flex justify-center gap-32 items-center">
    <h1 className="text-5xl font-bold tracking-wide">
      2048 게임을 디스코드 안에서.
    </h1>

    <div className="bg-[#2A2B30] px-2 pt-2 pb-0.5 rounded-lg">
      <Image
        src="/assets/screenshot-1.png"
        className="mr-12"
        alt="logo"
        width={320}
        height={320}
        priority
      />
    </div>
  </div>
);

const introPage2 = (
  <div className="w-screen px-16 bg-[#5048ed] h-screen flex justify-center gap-32 items-center">
    <div className="bg-[#2A2B30] px-2 pt-2 pb-0.5 rounded-lg">
      <Image
        src="/assets/screenshot-1.png"
        className="mr-12"
        alt="logo"
        width={320}
        height={320}
        priority
      />
    </div>
    <h1 className="text-5xl font-bold tracking-wide">
      2048 게임을 디스코드 안에서.
    </h1>
  </div>
);

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>메인 - 4096</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <ScrollContainer>
        <ScrollPage>
          <Animator animation={batch(Sticky(), MoveOut(0, -100), Fade())}>
            <div className="text-center">
              <h1 className="text-9xl font-bold tracking-wide pb-4">4096</h1>
              <h3 className="text-2xl font-medium pb-12">
                디스코드에서 즐기는 2048 게임봇
              </h3>

              <button
                type="button"
                className="px-5 py-3 bg-zinc-900/50 shadow-xl rounded-xl text-lg flex items-center mx-auto gap-2 hover:bg-zinc-600/40 transition-all duration-300"
                onClick={() => console.log('asdf')}
              >
                <a href="/">
                  <IconPlus className="inline-block" /> 서버에 초대하기
                </a>
              </button>
            </div>
          </Animator>
          <Animator animation={batch(Sticky(), Fade())}>
            <div className="relative w-screen">
              <div
                className="absolute left-0 right-0 text-center brightness-75 animate-bounce text-lg font-light"
                style={{
                  top: '42vh',
                }}
              >
                <IconChevronDown className="inline-block mr-2" />
                <span>스크롤하여 봇 소개 보기</span>
              </div>
            </div>
          </Animator>
        </ScrollPage>

        <ScrollPage>
          <></>
        </ScrollPage>

        <ScrollPage>
          <Animator
            animation={batch(Sticky(), FadeIn(), MoveIn(50, 0), ZoomIn())}
          >
            <h1 className="text-[180px] font-bold tracking-wide  mb-10">2¹²</h1>
          </Animator>
        </ScrollPage>

        <ScrollPage>
          <Animator animation={batch(Sticky())}>
            <h1 className="text-[180px] font-bold tracking-wide mb-10">2¹²</h1>
          </Animator>
        </ScrollPage>

        <ScrollPage>
          <Animator animation={batch(Sticky(), FadeIn())}>
            <h1 className="text-3xl font-medium tracking-wide mt-64">
              디스코드 미니 게임봇.
            </h1>
          </Animator>
        </ScrollPage>

        <ScrollPage>
          <Animator animation={batch(StickyIn())}>
            <h1 className="text-[180px] font-bold tracking-wide mb-10">2¹²</h1>
          </Animator>
          <Animator animation={batch(StickyIn())}>
            <h1 className="text-3xl font-medium tracking-wide mt-64">
              디스코드 미니 게임봇.
            </h1>
          </Animator>
        </ScrollPage>

        <ScrollPage>
          <Animator animation={batch(StickyIn(), Fade(), MoveIn(0, 700))}>
            {introPage1}
          </Animator>
        </ScrollPage>

        <ScrollPage>
          <Animator animation={batch(StickyIn())}>{introPage1}</Animator>
        </ScrollPage>

        <ScrollPage>
          <Animator animation={batch(StickyIn(), Fade(), MoveIn(0, 700))}>
            {introPage2}
          </Animator>
        </ScrollPage>
      </ScrollContainer>
    </>
  );
};

export default Home;
